# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foobar.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='foobar.proto',
  package='lorem',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x66oobar.proto\x12\x05lorem\".\n\x03\x42\x61z\x12\x13\n\x0bsomeInteger\x18\x01 \x01(\x05\x12\x12\n\nsomeString\x18\x02 \x01(\tb\x06proto3'
)




_BAZ = _descriptor.Descriptor(
  name='Baz',
  full_name='lorem.Baz',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='someInteger', full_name='lorem.Baz.someInteger', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='someString', full_name='lorem.Baz.someString', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=69,
)

DESCRIPTOR.message_types_by_name['Baz'] = _BAZ
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Baz = _reflection.GeneratedProtocolMessageType('Baz', (_message.Message,), {
  'DESCRIPTOR' : _BAZ,
  '__module__' : 'foobar_pb2'
  # @@protoc_insertion_point(class_scope:lorem.Baz)
  })
_sym_db.RegisterMessage(Baz)


# @@protoc_insertion_point(module_scope)
